# Generated by Django 5.2.5 on 2025-08-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('designated_attendee', models.CharField(choices=[('member1', 'Member 1'), ('member2', 'Member 2')], max_length=50)),
                ('document', models.FileField(upload_to='documents/')),
                ('category', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('employee', 'Employee'), ('intern', 'Intern')], max_length=50)),
            ],
        ),
    ]
