# Generated by Django 5.2.5 on 2025-08-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_receptionistuserauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionistuserauth',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
